name: PHPStan Analysis

on: [ push, pull_request ]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Create vendor Directory
        run: |
          echo Making directory...
          mkdir vendor
          echo Directory made.
      - name: Getting libEasyUI.phar
        uses: wei/wget@v1
        with:
          args: -O vendor/libEasyUI.phar https://poggit.pmmp.io/r/128037/libEasyUI_dev-10.phar
      - name: Run PHPStan
        uses: paroxity/pmmp-phpstan-action@master
        with:
          phpstan-config: phpstan.neon.dist
