--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/brokiem/SimpleNPC
build-by-default: true
branches:
- master
projects:
  SimpleNPC:
    path: ""
    icon: "/assets/logo.png"
    libs:
      - src: GiantQuartz/EasyUI/libEasyUI
        version: 1.0.0
...
