--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/brokiem/SimpleNPC
branches:
  - master
projects:
  SimpleNPC:
    path: ""
    icon: "/assets/image.png"
    libs:
      - src: brokiem/EasyUI/libEasyUI
        version: 1.0.0
    lint:
      phpstan: false
...