name: SimpleNPC
main: brokiem\snpc\SimpleNPC
version: 0.0.1
api: 3.15.0
author: brokiem

mcpe-protocol: [ 407, 408, 418, 419, 421, 422, 428 ]

permissions:
  snpc.*:
    default: op
  snpc.spawn:
    default: op
  snpc.edit:
    default: op
  snpc.remove:
    default: op
  snpc.migrate:
    default: op
  snpc.list:
    default: op
