name: SimpleNPC
main: brokiem\snpc\SimpleNPC
version: 0.0.1
api: 3.15.0
author: brokiem

permissions:
  snpc.*:
    default: op
  snpc.spawn:
    default: op
  snpc.edit:
    default: op
  snpc.remove:
    default: op
  snpc.list:
    default: op
