name: SimpleNPC
main: brokiem\snpc\SimpleNPC
version: 0.0.1
api: 3.15.0
author: brokiem
website: https://github.com/brokiem/SimpleNPC
mcpe-protocol: [ 407, 408, 418, 419, 421, 422, 428 ]
softdepend: [ "Slapper" ]

permissions:
  snpc.spawn:
    default: op
  snpc.edit:
    default: op
  snpc.remove:
    default: op
  snpc.migrate:
    default: op
  snpc.list:
    default: op
  snpc.rca:
    default: op
